import { expect, test, describe, beforeEach, afterEach } from 'vitest';
import fs from 'fs/promises';
import path from 'path';
import os from 'os';
import { pack } from '../../src/core/packager.js';
import { RepopackConfigFile, RepopackConfigMerged } from '../../src/config/configTypes.js';
import { loadFileConfig, mergeConfigs } from '../../src/config/configLoader.js';
import { isWindows } from '../testing/testUtils.js';

const fixturesDir = path.join(__dirname, '..', 'fixtures', 'packager');
const inputsDir = path.join(fixturesDir, 'inputs');
const outputsDir = path.join(fixturesDir, 'outputs');

describe.runIf(!isWindows)('packager integration', () => {
  const testCases = [{ name: 'simple-project', config: {} }];

  let tempDir: string;

  beforeEach(async () => {
    // Create a temporary directory for each test
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'repopack-test-'));
  });

  afterEach(async () => {
    // Clean up the temporary directory after each test
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  testCases.forEach(({ name }) => {
    test(`should correctly pack ${name}`, async () => {
      const inputDir = path.join(inputsDir, name);
      const expectedOutputPath = path.join(outputsDir, `${name}-output.txt`);
      const actualOutputPath = path.join(tempDir, 'repopack-output.txt');

      const fileConfig: RepopackConfigFile = await loadFileConfig(inputDir, null);
      const mergedConfig: RepopackConfigMerged = mergeConfigs(fileConfig, {
        output: {
          filePath: actualOutputPath,
        },
      });

      // Run the pack function
      await pack(inputDir, mergedConfig);

      // Read the actual and expected outputs
      let actualOutput = await fs.readFile(actualOutputPath, 'utf-8');
      let expectedOutput = await fs.readFile(expectedOutputPath, 'utf-8');

      actualOutput = actualOutput.replace(/^This file was generated by Repopack on:.*\n/gm, '');
      expectedOutput = expectedOutput.replace(/^This file was generated by Repopack on:.*\n/gm, '');

      // Compare the outputs
      expect(actualOutput).toBe(expectedOutput);

      // Optionally, update the expected output if explicitly requested
      if (process.env.UPDATE_EXPECTED_OUTPUT) {
        await fs.writeFile(expectedOutputPath, actualOutput);
        console.log(`Updated expected output for ${name}`);
      }
    });
  });
});
